from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    question: str = Field(..., min_length=2, description="User query or question to GraphRAG engine")


class ChatResponse(BaseModel):
    question: str = Field(..., description="Original user question")
    answer: str = Field(..., description="Grounded answer generated by GraphRAG agent")
    cache_hit: bool = Field(..., description="True if response was served from Redis Semantic Cache")
    route_decision: Optional[str] = Field(None, description="Router decision: vector, graph, or hybrid")
    sources: Dict[str, Any] = Field(default_factory=dict, description="Retrieved sources and metadata")
