import uuid
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    question: str = Field(..., min_length=1, description="User query or question to GraphRAG engine")
    tenant_id: Optional[str] = Field(
        None,
        description="Client/Tenant ID (optional if resolved from API Key header/query)",
        examples=["acme_corp"],
    )
    session_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Session identifier for multi-turn conversational memory",
        examples=["sess_user_12345"],
    )


class ChatResponse(BaseModel):
    tenant_id: str = Field(..., description="Tenant ID of the isolated workspace")
    session_id: str = Field(..., description="Active session ID for conversation continuity")
    question: str = Field(..., description="Original user question")
    answer: str = Field(..., description="Grounded answer generated by GraphRAG agent")
    cache_hit: bool = Field(..., description="True if response was served from Redis Semantic Cache")
    route_decision: Optional[str] = Field(None, description="Router decision: vector, graph, or hybrid")
    sources: Dict[str, Any] = Field(default_factory=dict, description="Retrieved sources and metadata")
